const data = [
  {
    id: 1,
    name: "McDonalds",
    icon: "/macDonalds.png",
    description: "Big Mac Jumbo",
    amount: 312,
    placeon: "12/12/2020",
    isEditing: false,
    status: {
      Confirmed: 156,
      Delivered: 106,
      'Refund Complated (30d)': 115,
      Pending: 11,
    },
  },
  {
    id: 2,
    name: "Tesla",
    description: "Model X",
    icon: "/Tesla.png",
    amount: 312,
    placeon: "12/12/2020",
    isEditing: false,
    status: {
      Confirmed: 459,
      Delivered: 12,
      'Refund Complated (30d)': 115,
      Pending: 12,
    },
  },
  {
    id: 3,
    name: "GM",
    description: "Alternative Car Parts",
    icon: "/GM.png",
    amount: 312,
    placeon: "12/12/2020",
    isEditing: false,
    status: {
      Confirmed: 357,
      Delivered: 12,
      'Refund Complated (30d)': 115,
      Pending: 12,
    },
  },
  {
    id: 4,
    name: "AARP",
    description: "Health care package Adult AI",
    icon: "/AARP.png",
    amount: 312,
    placeon: "12/12/2020",
    isEditing: false,
    status: {
      Confirmed: 456,
      Delivered: 12,
      'Refund Complated (30d)': 115,
      Pending: 12,
    },
  },
  {
    id: 5,
    name: "Disney",
    description: "Renewal Subscription",
    icon: "/Disney.png",
    amount: 450,
    placeon: "22/02/2023",
    isEditing: false,
    status: {
      Confirmed: 963,
      Delivered: 12,
      'Refund Complated (30d)': 115,
      Pending: 12,
    },
  },
  {
    id: 6,
    name: "Prime Therapeutics",
    description: "National oil",
    icon: "/Prime.png",
    amount: 123,
    placeon: "10/05/2025",
    isEditing: false,
    status: {
      Confirmed: 741,
      Delivered: 12,
      'Refund Complated (30d)': 115,
      Pending: 12,
    },
  },
  {
    id: 7,
    name: "Match.com",
    description: "Renewal Subscription",
    icon: "/Match.png",
    amount: 314,
    placeon: "23/07/2019",
    isEditing: false,
    status: {
      Confirmed: 789,
      Delivered: 12,
      'Refund Complated (30d)': 115,
      Pending: 12,
    },
  },
  {
    id: 8,
    name: "Chevy",
    description: "FX234A",
    icon: "/Chevy.png",
    amount: 102,
    placeon: "06/12/2015",
    isEditing: false,
    status: {
      Confirmed: 123,
      Delivered: 12,
      'Refund Complated (30d)': 115,
      Pending: 12,
    },
  },
  {
    id: 9,
    name: "GM",
    description: "Car Parts AJZ89B",
    icon: "/GM-car.png",
    amount: 159,
    placeon: "12/12/2020",
    isEditing: false,
    status: {
      Confirmed: 142,
      Delivered: 12,
      'Refund Complated (30d)': 115,
      Pending: 120,
    },
  },
];

export default data;
